services: docker

# Use container-based infrastructure
sudo: false

env:
  global:
    - IMAGE_NAME=michalolejniczak/visioon_pack

script:
  - docker build -t ${IMAGE_NAME}:${TRAVIS_BRANCH} .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ${IMAGE_NAME}:${TRAVIS_BRANCH}
